// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterService":       schema_pkg_apis_gp_v1alpha1_DBmasterService(ref),
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceSpec":   schema_pkg_apis_gp_v1alpha1_DBmasterServiceSpec(ref),
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceStatus": schema_pkg_apis_gp_v1alpha1_DBmasterServiceStatus(ref),
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeService":         schema_pkg_apis_gp_v1alpha1_DBnodeService(ref),
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceSpec":     schema_pkg_apis_gp_v1alpha1_DBnodeServiceSpec(ref),
		"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceStatus":   schema_pkg_apis_gp_v1alpha1_DBnodeServiceStatus(ref),
	}
}

func schema_pkg_apis_gp_v1alpha1_DBmasterService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBmasterService is the Schema for the dbmasterservices API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceSpec", "github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBmasterServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gp_v1alpha1_DBmasterServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBmasterServiceSpec defines the desired state of DBmasterService",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gp_v1alpha1_DBmasterServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBmasterServiceStatus defines the observed state of DBmasterService",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gp_v1alpha1_DBnodeService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBnodeService is the Schema for the dbnodeservices API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceSpec", "github.com/soxueren/greenplum-operator/pkg/apis/gp/v1alpha1.DBnodeServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gp_v1alpha1_DBnodeServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBnodeServiceSpec defines the desired state of DBnodeService",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_gp_v1alpha1_DBnodeServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DBnodeServiceStatus defines the observed state of DBnodeService",
				Type:        []string{"object"},
			},
		},
	}
}
